language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - sys-img-armeabi-v7a-android-26
  before_script:
    # Temp fix for constraint layout
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

    - echo yes | sdkmanager --licenses
    - echo yes | sdkmanager "platforms;android-26"
    - android create avd --force -n test -t android-26 --abi armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
